import { setRuntimeOverride, IN_NODE, type Runtime } from "./environments";
// Prevent TS errors for process in Node builds
declare const process: any;
/**
 * The main bootstrap code for loading pyodide.
 */
import {
  calculateDirname,
  loadScript,
  initNodeModules,
  resolvePath,
  calculateInstallBaseUrl,
} from "./compat";

import { createSettings } from "./emscripten-settings";
import { version as version_ } from "./version";

import type { PyodideAPI } from "./api.js";
import type {
  TypedArray,
  Module,
  PackageData,
  FSType,
  Lockfile,
} from "./types";
import type { EmscriptenSettings } from "./emscripten-settings";
import type { SnapshotConfig } from "./snapshot";
import { withTrailingSlash } from "./common/path";
export type { PyodideAPI, TypedArray, PyodideAPI as PyodideInterface };
export type { LockfileInfo, LockfilePackage, Lockfile } from "./types";

export { type PackageData };

/**
 * The Pyodide version.
 *
 * The version here is a Python version, following :pep:`440`. This is different
 * from the version in ``package.json`` which follows the node package manager
 * version convention.
 */
export const version: string = version_;

declare function _createPyodideModule(
  settings: EmscriptenSettings,
): Promise<Module>;

// BUILD_ID is generated from hashing together pyodide.asm.js and
// pyodide.asm.wasm in esbuild.config.outer.mjs
//
// It is used to check that memory snapshots were generated by the same build of
// the runtime that is trying to use them. Attempting to use a snapshot from a
// different build will fail badly. See logic in snapshot.ts.
declare const BUILD_ID: string;

/**
 * See documentation for loadPyodide.
 * @hidden
 */
export type ConfigType = {
  indexURL: string;
  packageCacheDir: string;
  lockFileContents: Lockfile | string | Promise<Lockfile | string>;
  fullStdLib?: boolean;
  stdLibURL?: string;
  stdin?: () => string;
  stdout?: (msg: string) => void;
  stderr?: (msg: string) => void;
  jsglobals?: object;
  _sysExecutable?: string;
  args: string[];
  fsInit?: (FS: FSType, info: { sitePackages: string }) => Promise<void>;
  env: { [key: string]: string };
  packages: string[];
  _makeSnapshot: boolean;
  enableRunUntilComplete: boolean;
  checkAPIVersion: boolean;
  BUILD_ID: string;
  packageBaseUrl?: string;
  cdnUrl: string;
};

/**
 * Load the main Pyodide wasm module and initialize it.
 *
 * @returns The :ref:`js-api-pyodide` module.
 * @example
 * async function main() {
 *   const pyodide = await loadPyodide({
 *     fullStdLib: true,
 *     stdout: (msg) => console.log(`Pyodide: ${msg}`),
 *   });
 *   console.log("Loaded Pyodide");
 * }
 * main();
 */

// Extended options type that includes runtime override
export interface LoadPyodideOptions extends Partial<ConfigType> {
  runtime?: Runtime;
  indexURL?: string;
  lockFileURL?: string;
  packageBaseUrl?: string;
  pyproxyToStringRepr?: boolean;
  convertNullToNone?: boolean;
  _loadSnapshot?: ArrayBuffer | Uint8Array | Promise<ArrayBuffer | Uint8Array>;
  _snapshotDeserializer?: (obj: any) => any;
}

export async function loadPyodide(
  options: LoadPyodideOptions = {},
): Promise<PyodideAPI> {
  // Apply runtime override; if 'auto' or null is passed, use normal auto-detection
  if (options.runtime !== undefined) {
    setRuntimeOverride(options.runtime);
  }

  if (options.lockFileContents && options.lockFileURL) {
    throw new Error("Can't pass both lockFileContents and lockFileURL");
  }
  // Run initNodeModules only in Node environment
  if (IN_NODE) {
    await initNodeModules();
  }

  // Compute indexURL (supports both file:// and http(s)://)
  let indexURL: string;
  {
    const raw = options.indexURL || (await calculateDirname());
    if (/^(file|https?):\/\//.test(raw)) {
      indexURL = withTrailingSlash(raw);
    } else {
      const base = globalThis.location?.href ?? 
    `file://${(globalThis as any).process?.cwd?.() ?? '.'}/`;
      indexURL = new URL(withTrailingSlash(resolvePath(raw)), base).href;
    }
  }
  const options_ = options as ConfigType;

  options_.packageBaseUrl = withTrailingSlash(options_.packageBaseUrl);
  // cdnUrl only for node. withTrailingSlash is a no-op, but just in case to prevent future human errors.
  options_.cdnUrl = withTrailingSlash(
    options_.packageBaseUrl ??
      `https://cdn.jsdelivr.net/pyodide/v${version}/full/`,
  );

  if (!options.lockFileContents) {
    const lockFileURL = options.lockFileURL ?? new URL("pyodide-lock.json", indexURL).href;
    options_.lockFileContents = loadLockFile();  // Modified to use the new function
    // packageBaseUrl isn't present, try using base location of lockFileUrl. If
    // lockFileURL is relative, use location as the base URL.
    options_.packageBaseUrl ??= calculateInstallBaseUrl(lockFileURL);
    }
  options_.indexURL = indexURL;

  if (options_.packageCacheDir) {
    options_.packageCacheDir = withTrailingSlash(
      resolvePath(options_.packageCacheDir),
    );
  }

  const default_config = {
    fullStdLib: false,
    jsglobals: globalThis,
    stdin: globalThis.prompt ? globalThis.prompt : undefined,
    args: [],
    env: {},
    packages: [],
    packageCacheDir: options_.packageBaseUrl,
    enableRunUntilComplete: true,
    checkAPIVersion: true,
    BUILD_ID,
  };
  const config = Object.assign(default_config, options_) as ConfigType;
  config.env.HOME ??= "/home/pyodide";
  /**
   * `PyErr_Print()` will call `exit()` if the exception is a `SystemError`.
   * This shuts down the Python interpreter, which is a change in behavior from
   * what happened before. In order to avoid this, we set the `inspect` config
   * parameter which prevents `PyErr_Print()` from calling `exit()`. Except in
   * the cli runner, we actually do want to exit. So set default to true and in
   * cli runner we explicitly set it to false.
   */
  config.env.PYTHONINSPECT ??= "1";
  const emscriptenSettings = createSettings(config);
  const API = emscriptenSettings.API;
  API.lockFilePromise = Promise.resolve(options_.lockFileContents);

  // If the pyodide.asm.js script has been imported, we can skip the dynamic import
  // Users can then do a static import of the script in environments where
  // dynamic importing is not allowed or not desirable, like module-type service workers
  if (typeof _createPyodideModule !== "function") {
    const scriptSrc = `${config.indexURL}pyodide.asm.js`;
    await loadScript(scriptSrc);
  }

  let snapshot: Uint8Array | undefined = undefined;
  if (options._loadSnapshot) {
    const snp = await options._loadSnapshot;
    if (ArrayBuffer.isView(snp)) {
      snapshot = new Uint8Array(snp.buffer, snp.byteOffset, snp.byteLength);
    } else {
      snapshot = new Uint8Array(snp);
    }
    emscriptenSettings.noInitialRun = true;
    emscriptenSettings.INITIAL_MEMORY = snapshot.length;
  }

  // _createPyodideModule is specified in the Makefile by the linker flag:
  // `-s EXPORT_NAME="'_createPyodideModule'"`
  const Module = await _createPyodideModule(emscriptenSettings);
  // Handle early exit
  if (emscriptenSettings.exitCode !== undefined) {
    throw new Module.ExitStatus(emscriptenSettings.exitCode);
  }
  if (options.pyproxyToStringRepr) {
    API.setPyProxyToStringMethod(true);
  }
  if (options.convertNullToNone) {
    API.setCompatNullToNone(true);
  }

  if (API.version !== version && config.checkAPIVersion) {
    throw new Error(`\
Pyodide version does not match: '${version}' <==> '${API.version}'. \
If you updated the Pyodide version, make sure you also updated the 'indexURL' parameter passed to loadPyodide.\
`);
  }
  // Disable further loading of Emscripten file_packager stuff.
  Module.locateFile = (path: string) => {
    if (path.endsWith(".so")) {
      throw new Error(`Failed to find dynamic library "${path}"`);
    }
    throw new Error(`Unexpected call to locateFile("${path}")`);
  };

  let snapshotConfig: SnapshotConfig | undefined = undefined;
  if (snapshot) {
    snapshotConfig = API.restoreSnapshot(snapshot);
  }
  // runPython works starting after the call to finalizeBootstrap.
  const pyodide = API.finalizeBootstrap(
    snapshotConfig,
    options._snapshotDeserializer,
  );
  API.sys.path.insert(0, "");

  API._pyodide.set_excepthook();
  await API.packageIndexReady;
  // I think we want this initializeStreams call to happen after
  // packageIndexReady? I don't remember why.
  API.initializeStreams(config.stdin, config.stdout, config.stderr);
  return pyodide;
}

/**
 * Load and parse the pyodide lock file
 * @returns Promise<Lockfile> The parsed lock file contents
 */
async function loadLockFile(): Promise<Lockfile> {
    const baseUrl = (globalThis as any).process?.env?.PYODIDE_BASE_URL ?? ".";
    const url = `${baseUrl}/pyodide-lock.json`;
    const res = await fetch(url);
    if (!res.ok) {
        throw new Error(`Failed to fetch lock file: ${res.status}`);
    }
    return await res.json();
}
